# Generated by Django 4.1.7 on 2023-03-18 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_comment_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
