# Generated by Django 4.2.4 on 2023-08-14 23:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0005_rename_text_comment_content_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="creation_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 8, 14, 23, 39, 57, 465506)
            ),
        ),
    ]
