# Generated by Django 4.2.4 on 2023-08-17 17:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_user_followers_alter_user_following"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="banner",
        ),
        migrations.AlterField(
            model_name="user",
            name="genre",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "JZ"),
                    (1, "RB"),
                    (2, "HH"),
                    (3, "IN"),
                    (4, "FK"),
                    (5, "IE"),
                    (6, "PP"),
                ],
                default=5,
            ),
        ),
    ]
