# Generated by Django 4.1.7 on 2023-03-18 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='banner',
            field=models.URLField(blank=True, default='https://cdn.pixabay.com/photo/2014/01/15/12/44/classical-music-245590_1280.jpg'),
        ),
        migrations.AddField(
            model_name='user',
            name='genre',
            field=models.CharField(choices=[('JZ', 'Jazz'), ('RB', 'R&B / Soul'), ('HH', 'Hip-Hop'), ('IN', 'Classical'), ('FK', 'Folk / Acoustic'), ('IE', 'Indie / Alternative'), ('PP', 'Pop')], default='IE', max_length=2),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.URLField(blank=True, default='https://static.vecteezy.com/system/resources/thumbnails/004/582/531/small/music-note-icon-design-symbol-music-note-sound-melody-musical-for-multimedia-free-vector.jpg'),
        ),
    ]
