# Generated by Django 4.2 on 2023-04-15 22:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_post_image_alter_comment_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 15, 22, 49, 34, 744617)),
        ),
    ]
